Userstory/12 (Converter implementation) is done
PanicControlSolution/Project pull request #23
Opened 2023-04-16 21:43 UTC by ALFecki

2023-04-17 07:49 UTC, PaShampusik submitted a review, later dismissed

2023-04-17 10:41 UTC, VadVergasov commented on Lab5.UI/Pages/Sets.xaml
> +                Title="Выберите сет"
Вот это изменение))))

2023-04-17 10:43 UTC, VadVergasov requested changes

2023-04-17 10:43 UTC, VadVergasov commented on Lab5.UI/Pages/Sets.xaml
> +
Ctrl+k, Ctrk+D

2023-04-17 15:07 UTC, ALFecki commented on Lab5.UI/Pages/Sets.xaml
> +                Title="Выберите сет"
А я резко вспомнил, что ты топил за русский язык

2023-04-17 15:08 UTC, ALFecki commented on Lab5.UI/ValueConverters/CountToColorValueConverter.cs
> +            if (count > 8)
Как же мне не нравится этот мягкий знак в слове "нравитЬся" :D

2023-04-17 15:15 UTC, VadVergasov commented on Lab5.UI/MauiProgram.cs
> +            services.AddSingleton(new AppDbContext(options));
Это что?

2023-04-17 15:15 UTC, VadVergasov commented on Lab5.UI/Lab5.UI.csproj
> +		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.5" />
И это откуда

2023-04-17 15:35 UTC, VadVergasov commented on Lab5.UI/Pages/Sets.xaml
> +                Title="Выберите сет"
Когда

2023-04-18 11:36 UTC, PaShampusik submitted a review, later dismissed

2023-04-18 11:39 UTC, PaShampusik approved these changes

2023-04-18 11:39 UTC, VadVergasov approved these changes

2023-04-18 11:55 UTC, merged