userstory13
PanicControlSolution/Project pull request #24
Opened 2023-04-17 07:44 UTC by PaShampusik

2023-04-17 10:51 UTC, VadVergasov commented
Что тут происходит с историей коммитов, жесть

2023-04-17 10:56 UTC, VadVergasov requested changes

2023-04-17 10:56 UTC, VadVergasov commented on Lab5.UI/AppShell.xaml
> +                  Route="MainPage"/>
Верни как было

2023-04-17 10:56 UTC, VadVergasov commented on Lab5.UI/Pages/Sets.xaml
> +<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:models="clr-namespace:Lab5.UI.ViewModels" xmlns:entities="clr-namespace
Надо поправить форматирование всего файла

2023-04-17 15:12 UTC, ALFecki approved these changes

2023-04-18 08:13 UTC, VadVergasov approved these changes

2023-04-18 08:13 UTC, merged